definitions:
  getCode.GetPhoneCode:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  getCode.ResCode:
    properties:
      body:
        $ref: '#/definitions/getCode.GetPhoneCode'
      mgsCode:
        description: 返回体状态码
        type: integer
      mgsText:
        description: 返回体信息
        type: string
    required:
    - mgsCode
    - mgsText
    type: object
  login.User:
    properties:
      id:
        type: string
      name:
        type: string
      token:
        type: string
    type: object
  login.UserBody:
    properties:
      body:
        $ref: '#/definitions/login.User'
      mgsCode:
        description: 返回体状态码
        type: integer
      mgsText:
        description: 返回体信息
        type: string
    required:
    - mgsCode
    - mgsText
    type: object
  login.UserCode:
    properties:
      code:
        type: string
      phone:
        type: string
    required:
    - code
    - phone
    type: object
  login.UserName:
    properties:
      password:
        description: 用户密码
        type: string
      phone:
        description: 用户名
        type: string
    required:
    - password
    - phone
    type: object
  login.UserSignReps:
    properties:
      body:
        type: string
      mgsCode:
        description: 返回体状态码
        type: integer
      mgsText:
        description: 返回体信息
        type: string
    required:
    - mgsCode
    - mgsText
    type: object
  login.UserSignType:
    properties:
      code:
        description: 手机验证码
        type: string
      password:
        description: 用户密码
        type: string
      phone:
        description: 用户名
        type: string
    required:
    - code
    - password
    - phone
    type: object
  uploadFiles.FilesRes:
    properties:
      body:
        type: string
      mgsCode:
        description: 返回体状态码
        type: integer
      mgsText:
        description: 返回体信息
        type: string
    required:
    - mgsCode
    - mgsText
    type: object
info:
  contact: {}
paths:
  /api/login/user/login:
    post:
      operationId: LoginInPasswordPaths
      parameters:
      - description: JSON数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/login.UserName'
      responses:
        "200":
          description: JSON数据
          schema:
            items:
              $ref: '#/definitions/login.UserBody'
            type: array
      summary: 用户登录操作
      tags:
      - Login
  /api/login/user/login_code:
    post:
      operationId: LoginsUserCode
      parameters:
      - description: JSON数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/login.UserCode'
      responses:
        "200":
          description: JSON数据
          schema:
            items:
              $ref: '#/definitions/login.UserBody'
            type: array
      summary: 用户登录操作
      tags:
      - Login
  /api/login/user/sign:
    post:
      operationId: LoginNewsUserPaths
      parameters:
      - description: JSON数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/login.UserSignType'
      responses:
        "200":
          description: JSON数据
          schema:
            $ref: '#/definitions/login.UserSignReps'
      summary: 用户注册操作
      tags:
      - Login
  /api/phone_code/user/{phone}:
    get:
      consumes:
      - application/json
      operationId: GetPathsCode
      parameters:
      - description: 用户手机号
        in: path
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: JSON数据
          schema:
            $ref: '#/definitions/getCode.ResCode'
      summary: 用户验证码登录
      tags:
      - Code
  /api/upload/deleteImg:
    get:
      operationId: UploadImagesDelete
      parameters:
      - description: 图片名称
        in: query
        name: name
        required: true
        type: string
      responses:
        "200":
          description: JSON数据
          schema:
            $ref: '#/definitions/uploadFiles.FilesRes'
      summary: 删除图片操作
      tags:
      - Upload
  /api/upload/images:
    post:
      operationId: UploadImages
      parameters:
      - description: file
        in: formData
        name: image
        required: true
        type: file
      responses:
        "200":
          description: JSON数据
          schema:
            $ref: '#/definitions/uploadFiles.FilesRes'
      summary: 上传图片操作
      tags:
      - Upload
  /api/upload/videos:
    post:
      operationId: UploadVideos
      parameters:
      - description: file
        in: formData
        name: videos
        required: true
        type: file
      responses:
        "200":
          description: JSON数据
          schema:
            $ref: '#/definitions/uploadFiles.FilesRes'
      summary: 上传视频操作
      tags:
      - Upload
swagger: "2.0"
